#!/usr/bin/env python3
"""From-scratch verifier for the Key Lemma certificates (and the direct per-m certificates).
Usage: verify_kl.py [--full] [--no-proof] [--dir=kl_certs]       (PASS/FAIL on the last line; exit code 0 iff PASS)

1. cnflib self-test.
2. Every certificate in kl_certs/ (prefix.cert.json.xz + prefix.cnf.xz) is checked by klcheck.py
   (base CNF regenerated from the recorded options, theory lemmas re-derived + exact Farkas,
   CNF = base + cube units + lemma clauses exactly), then its CNF is re-solved by CaDiCaL with a
   proof: DRAT -> drat-trim -> LRAT -> cake_lpr (or, if the CNF is large, CaDiCaL LRAT -> cake_lpr).
3. MANIFEST (fixed here, independent of file names): the required cells are
     B  : case t2, duplicate-padding model, R = 14, not1pair, nbr, E rows;
     A_s: case t1, exact model (distinct rows, weights >= 1e-5), R = s, third, nbr, E rows, s = 9..14.
   Each certificate is assigned to the cell whose option set it matches EXACTLY (options read from
   the certificate and already validated by klcheck through regeneration of the base CNF).  A cell is
   covered by one certificate without cube units, or by a family of cube certificates such that every
   assignment of the union of their cube literals satisfies some cube (exhaustive check; overlaps and
   refined sub-cubes are allowed, since lemmas do not depend on the cube).  Anything else (unassigned
   certificate, uncovered assignment) fails.
4. Direct per-m certificates proofs/direct_m{5,6,7}.cnf (and m=9 with --full): regenerated by
   gen_direct.py, clause-by-clause equal to the stored CNF, re-solved with DRAT, drat-trim, cake_lpr."""
import sys, os, json, lzma, subprocess, tempfile, glob, itertools
SAT = os.path.expanduser(os.environ.get('SAT_TOOLS', '~/claude_projects/sat'))  # dir with cadical/, drat-trim/, cake_lpr/
full = '--full' in sys.argv; noproof = '--no-proof' in sys.argv
CDIR = next((a.split('=', 1)[1] for a in sys.argv if a.startswith('--dir=')), 'kl_certs')
os.chdir(os.path.dirname(os.path.abspath(__file__)))
ok = True
def say(flag, msg):
    global ok
    ok &= flag; print(('PASS ' if flag else 'FAIL ') + msg, flush=True)
def sh(cmd): return subprocess.run(cmd, shell=True, capture_output=True, text=True)
def unsat_proof(cnf, d):
    big = os.path.getsize(cnf) > 200_000_000
    if not big:
        r = sh(f'nice -n 10 {SAT}/cadical/build/cadical -q --binary=false {cnf} {d}/p.drat')
        if 's UNSATISFIABLE' not in r.stdout: return 'cadical: ' + r.stdout[-80:]
        if 's VERIFIED' not in sh(f'nice -n 10 {SAT}/drat-trim/drat-trim {cnf} {d}/p.drat -L {d}/p.lrat -t 50000').stdout: return 'drat-trim'
    else:
        r = sh(f'nice -n 10 {SAT}/cadical/build/cadical -q --lrat=true --binary=false {cnf} {d}/p.lrat')
        if 's UNSATISFIABLE' not in r.stdout: return 'cadical: ' + r.stdout[-80:]
    if 's VERIFIED UNSAT' not in sh(f'nice -n 10 {SAT}/cake_lpr/cake_lpr {cnf} {d}/p.lrat').stdout: return 'cake_lpr'
    return None
say(sh('nice -n 10 python3 ../scripts/cnflib.py').returncode == 0, 'cnflib self-test')
COMMON = dict(sqs=False, useE=True, nbr=True, useF=False, wsort=False, notrade=False)
CELLS = {'B': dict(COMMON, case='t2', R=14, exact=False, third=False, not1pair=True)}
for s in range(9, 15): CELLS[f'A{s}'] = dict(COMMON, case='t1', R=s, exact=True, third=True, not1pair=False)
assigned = {c: [] for c in CELLS}
for cj in sorted(glob.glob(f'{CDIR}/*.cert.json.xz')):
    name = os.path.basename(cj)[:-len('.cert.json.xz')]
    with tempfile.TemporaryDirectory() as d:
        pre = os.path.join(d, name)
        open(pre + '.cert.json', 'wb').write(lzma.open(cj).read())
        open(pre + '.cnf', 'wb').write(lzma.open(f'{CDIR}/{name}.cnf.xz').read())
        r = sh(f'nice -n 10 python3 klcheck.py {pre}')
        good = r.returncode == 0 and r.stdout.startswith('PASS')
        say(good, f'klcheck {name}: ' + (r.stdout.strip() or r.stderr.strip()[-200:]))
        if not good: continue
        D = json.load(open(pre + '.cert.json'))
        opts = {k: D.get(k, False) for k in ('case', 'R', 'exact', 'third', 'not1pair', 'sqs', 'useE', 'nbr', 'useF', 'wsort', 'notrade')}
        cell = [c for c, spec in CELLS.items() if all(opts[k] == v for k, v in spec.items())]
        say(len(cell) == 1, f'{name} assigned to manifest cell {cell}')
        if len(cell) == 1: assigned[cell[0]].append((name, D.get('cube')))
        if noproof: continue
        err = unsat_proof(pre + '.cnf', d)
        say(err is None, f'{name} UNSAT proof checked' + ('' if err is None else f' ({err})'))
for c, lst in assigned.items():
    if any(not cube for _, cube in lst):
        mono = [n for n, cube in lst if not cube]
        say(True, f'cell {c} covered by monolithic certificate {mono[0]}'); continue
    if not lst:
        say(False, f'cell {c}: no certificate'); continue
    # cube certificates: every assignment of the union K of their literals must satisfy >= 1 cube
    cubes = [{tuple(l[0]): l[1] for l in cube} for _, cube in lst]
    if any(len(cu) != len(cube) for cu, (_, cube) in zip(cubes, lst)):
        say(False, f'cell {c}: a cube repeats a literal'); continue
    K = sorted(set(k for cu in cubes for k in cu))
    covered = all(any(all(asg[K.index(k)] == v for k, v in cu.items()) for cu in cubes)
                  for asg in itertools.product((0, 1), repeat=len(K)))
    say(covered, f'cell {c} covered by {len(lst)} cube certificates over {len(K)} literals '
                 f'(every one of the 2^{len(K)} assignments lies in some cube)')
for m in ([] if noproof else [5, 6, 7, 9] if full else [5, 6, 7]):
    with tempfile.TemporaryDirectory() as d:
        g = os.path.join(d, 'g.cnf'); sh(f'python3 gen_direct.py {m} {g} --pair')
        body = lambda f: [l for l in open(f) if not l.startswith('c')]
        same = body(g) == body(f'proofs/direct_m{m}.cnf')
        say(same, f'direct m={m}: stored CNF regenerated clause-for-clause by gen_direct.py')
        err = unsat_proof(f'proofs/direct_m{m}.cnf', d)
        say(err is None, f'direct m={m}: UNSAT proof checked' + ('' if err is None else f' ({err})'))
print('VERIFY_KL:', 'PASS' if ok else 'FAIL'); sys.exit(0 if ok else 1)
